Fix CS0121 compiler error when building with SDK v8.0.108
This code was updated a few months ago [1] to avoid 'Use collection
expression for array' (IDE0300) code analysis warnings when building
with .NET SDK v8.0.300. However that change introduced the following
error when building using the latest SDK in the 8.0.1xx feature band:

  error CS0121: The call is ambiguous between the following methods or
  properties: 'ClaimsIdentity.ClaimsIdentity(IEnumerable<Claim>?)' and
  'ClaimsIdentity.ClaimsIdentity(string?)'

[1] d8b55ec2ba9d301b08cc28609ceb4860b8778ce6